#!/usr/bin/env python3
"""check_doc_module_counts.py — CLAIMS-AUDIT-001 / REVIEWER-FRICTION-002,007 gate.

ci/sync_module_count.py keeps a curated set of docs in sync with the runner, but
several REVIEWER-FACING files carry hand-written module/workflow counts that escape
that set and went stale (e.g. "254 exploit PoC modules ... 37 CI workflows",
"249 modules / 60 non-exploit", "400-module unified runner").

Scope is deliberately narrow to avoid false positives:
  * only the curated SCANNED list below (reviewer/claim docs, NOT changelogs),
  * only unambiguous composite phrases that clearly denote the audit totals,
  * lines that look historical (a date, a "->"/"→" delta) are skipped.

Counts are checked against docs/canonical_data.json (regenerated by
ci/build_canonical_data.py from audit/unified_audit_runner.cpp).

Exit 0 = all scanned counts match canonical, 1 = stale count found.
"""
import json
import re
import sys
from pathlib import Path

CANON = Path("docs/canonical_data.json")

# Curated reviewer/claim files only. Changelogs and historical reports are excluded
# on purpose — their point-in-time counts must NOT be rewritten.
SCANNED = [
    "README.md",
    "docs/BITCOIN_CORE_PR_BODY.md",
    "docs/BITCOIN_CORE_PR_DESCRIPTION.md",
    "docs/INTEGRATION_PATCH.patch",
    "docs/CROSS_PLATFORM_TEST_MATRIX.md",
    "docs/BACKEND_PARITY.md",
    "docs/TEST_MATRIX.md",
]

# Lines matching these are historical context, not a live claim — skip them.
HISTORICAL = re.compile(r"(->|→|\b20\d\d-\d\d\b|catalogued|\badded\)|\bremoved\b)")

# (regex, tuple-of-keys-per-group, label)
RULES = [
    # "N modules (X non-exploit + Y exploit PoCs)"
    (re.compile(r"(\d+)\s+modules\s*\(\s*(\d+)\s+non-exploit\s*\+\s*(\d+)\s+exploit\s+PoCs?", re.I),
     ("total_modules", "non_exploit_modules", "exploit_poc_count"), "module breakdown"),
    # "(X non-exploit + Y exploit PoCs = N modules)"  (BACKEND_PARITY style)
    (re.compile(r"\(\s*(\d+)\s+non-exploit\s*\+\s*(\d+)\s+exploit\s+PoCs?\s*=\s*(\d+)\s+modules", re.I),
     ("non_exploit_modules", "exploit_poc_count", "total_modules"), "reversed breakdown"),
    # "N-module unified runner" / "N module unified runner"
    (re.compile(r"(\d+)[\s-]+module\s+unified\s+runner", re.I),
     ("total_modules",), "unified-runner module count"),
    # "N exploit PoC modules" (the INTEGRATION_PATCH phrase — 'modules' required)
    (re.compile(r"(\d+)\s+exploit\s+PoC\s+modules", re.I),
     ("exploit_poc_count",), "exploit PoC module count"),
    # "N CI workflows"
    (re.compile(r"(\d+)\s+CI\s+workflows", re.I),
     ("ci_workflow_count",), "CI workflow count"),
]


def fail(msg: str) -> None:
    print(f"::error::check_doc_module_counts: {msg}")


def main() -> int:
    if not CANON.exists():
        print(f"check_doc_module_counts: {CANON} not found — run from submodule root")
        return 1
    canon = json.loads(CANON.read_text())

    errors = 0
    for rel in SCANNED:
        doc = Path(rel)
        if not doc.exists():
            continue
        for ln_idx, line in enumerate(doc.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            if HISTORICAL.search(line):
                continue
            for rx, keys, label in RULES:
                for m in rx.finditer(line):
                    for gi, k in enumerate(keys, 1):
                        got = int(m.group(gi))
                        if got != canon[k]:
                            fail(f"{rel}:{ln_idx}: {label} = {got} != canonical "
                                 f"{k}={canon[k]}  ::  {line.strip()[:90]}")
                            errors += 1

    if errors:
        print(f"check_doc_module_counts: {errors} stale reviewer-doc count(s) — fix them "
              "(canonical is docs/canonical_data.json; run ci/build_canonical_data.py first)")
        return 1
    print(f"check_doc_module_counts: all counts in {len(SCANNED)} reviewer docs match "
          "docs/canonical_data.json [PASS]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
